### PR TITLE
Bugfix/d sstore

### LINKED ISSUE #218: Remove  .DS_Store
This file shouldn't be committed

### PR DESCRIPTION
**Pull request by delagroove**
Resolves #218

### CODE REVIEW

**Comment by brent-hoover** [comment]
@delagroove Did you also mean to bump the versions on everything?

**Comment by delagroove** [comment]
@zenweasel  There's a PR there that Akarshit needs to finish for that.

**Comment by brent-hoover** [comment]
It looks like you already bumped them here though, was that on purpose?

**Comment by delagroove** [comment]
yes, in order to leave them with the correct values.

**Pull request merged**
