### PR TITLE
Release configurations

### PR DESCRIPTION
**Pull request by ticean**
Impact: **minor**  
Type: **feature**

## Issue
Changes to add versioned releases to the project. We now have a repository of releases since `v3.0.0`. Also includes tooling to get local state synced with configured remotes. Includes docs on how config works and how to select a specific release version.

### How Configuration Works

_This is not changed. Only added documentation._

The Reaction development platform uses `make` to run tasks. `make` is aware of
the task dependency tree and ensures that all required dependencies are met
when running a task.  The main tasks and functionality for `make` are
configured in `Makefile`.

Configurations that may change are extracted into `config.mk`. This file is
checked in to source control and should not be modified. It is always configured
for the latest Reaction release.

If a file named `config.local.mk` exists then it will be loaded after
`config.mk`. Settings in `config.local.mk` will override those set in
`config.mk`. It is ignored by source control.

### Running a Specific Reaction Release Version

Configurations for specific Reaction releases (since v3.0.0) are located in
`config/reaction-oss`. You may symlink or copy any release configuration to
`config.local.mk`.

For example, this command will configure the platform to run `v3.0.4`:

```sh
ln -s config/reaction-oss/reaction-v3.0.4.mk
make
```
### Running A Completely Customized Installation

You may customize your Reaction installation by modifying `config.local.mk`.
It's easiest to start with an existing release configuration file and modify it
as needed. In this way you can:

    * Add new sub-projects
    * Remove sub-projects
    * Update the git origin for a sub-project
    * Change the default branch for a sub-project
    * Customize the lifecycle hooks directory to run custom scripts for automation

Configuration files store in `config/local` are ignored by git. It's a
convenient place to store local files for quick development. If you are sharing
files with a team then you may want to keep your configuration files in a
separate git repository or in shared network storage.

The only requirement to override configuration is that you need to put a file
into place at `config.local.mk`, so it is possible to copy or symlink a file
from anywhere in your system.

Examples:

```sh
ln -s config/local/my-custom-config.mk config.local.mk
make
```

```sh
ln -s /path/on/my/system/reactionconfig.mk config.local.mk
make
```

### Updating Local Branches to Match Config

If you are using the Reaction development platform for development, then you
will need to update your local branch to get the latest at some point. The
`update-checkouts` command will perform this operation.

```
make update-checkouts
```

The command is safe. It will halt if there are uncommitted changes in
git before doing anything. You may commit, stash or drop those changes.

## Breaking changes
None. Please see changes to release process.

## Changes to Release Process
This change will imply changes to the release process.

1. `config.mk` should be updated to reflect latest. We do this today, so no change here.
2. The updated `config.mk` should be copied into the `config/reaction-oss` directory. This is new.
3. It's no longer `required` to tag this repository with the Reaction version because all releases are in the config directory.
4. Changes to this repository should be checked for compatibility with the release configurations.

## Testing
```sh
# Clone the reaction-development-platform, as usual.
git clone git@github.com:reactioncommerce/reaction-development-platform.git
cd reaction-development-platform

# Download a shared config file.
curl https://gist.githubusercontent.com/ticean/00d94c82ec4bf45210d2cd2a3d41a586/raw/753edd1abf0d8ecb615fec3ce122a5f35bed8764/reaction-v3.0.4.custom.mk \
  > config/local/reaction-v3.0.4.custom.mk

# Symlink the downloaded file to `config.local.mk`.
ln -s ./config/local/reaction-v3.0.4.custom.mk config.local.mk

# Do the usual setup.
make
```

### CODE REVIEW

**Review by aldeed — APPROVED** [review]
I did not review the code, but 👍for this approach.

**Comment by ticean** [comment]
Here's a demonstration and example that can be used for testing:

```sh
# Clone the reaction-development-platform, as usual.
git clone git@github.com:reactioncommerce/reaction-development-platform.git
cd reaction-development-platform

# Download a shared config file.
curl https://gist.githubusercontent.com/ticean/00d94c82ec4bf45210d2cd2a3d41a586/raw/753edd1abf0d8ecb615fec3ce122a5f35bed8764/reaction-v3.0.4.custom.mk \
  > config/local/reaction-v3.0.4.custom.mk

# Symlink the downloaded file to `config.local.mk`.
ln -s ./config/local/reaction-v3.0.4.custom.mk config.local.mk

# Do the usual setup.
make
```

**Comment by focusaurus** [comment]
I'm thinking if these files are about to proliferate, we should probably re-evaluate a partial makefile as the data format. Don't want to open a huge can of worms but should we consider maybe TOML or JSON?

Is there some way the external prereqs and networks necessary can be handled differently? Could we consider the `docker-compose.yml` files as the source of truth for networks and parse those to create as needed? Could the projects themselves define prereqs and dev-platform just enumerates through those to do its checks?

**Comment by ticean** [comment]
Hey @focusaurus. This PR conceptually separates the runner (`reaction-development-platform`) from what it runs (the config). No changes to the configuration format at all.

I'd rather not hold up workflow the benefits of the versioned manifests because we'd prefer another config language. I don't see enough payoff to make that worth it a high-level of effort. Happy to talk through formatting as a follow up, though, if you have ideas for an implementation.

---

re: proliferation: In the PR's first commit, I moved the hooks directory to the `Makefile` so that it doesn't have to be added to each config file. I considered defaulting `REQUIRED_SOFTWARE` and `DOCKER_NETWORKS` , too, but doing so that increases the risk of config files behaving differently across platform versions. I opted to make them explicit in each config to guarantee the same results on every run.

**Comment by rosshadden** [comment]
Having multiple versions per reaction-oss (for example) seems a little rough given that we no longer have lock-step versions. I don't think we should have a file for every permutation of every version of every project, but the other extreme doesn't seem great either (which is what is committed here, where reaction is the only project with version changes between sibling files). I think it would be more in line with our current versioning workflow to have `config/reaction-oss.mk` and encouraging people to make their own with their own modifications as needed.

Edit: In case that is muddled, I'm basically proposing we get rid of the nesting inside `config`, and remove all but one of the `reaction-v3.x.x` prefab files from the repo.

**Comment by ticean** [comment]
@rosshadden The versioned configurations correspond to actual Reaction releases since v3.0.0. They encompass all the projects and pin each project to the version _tested for the release._

These configs already exist. The content of each config file was copied from the `config.mk` content at the corresponding git tag in this project. Here are links to those original tagged versions (not the files in this pr):

* [v3.0.0](https://github.com/reactioncommerce/reaction-development-platform/blob/v3.0.0/config.mk)
* [v3.0.1](https://github.com/reactioncommerce/reaction-development-platform/blob/v3.0.1/config.mk)
* [v3.0.2](https://github.com/reactioncommerce/reaction-development-platform/blob/v3.0.2/config.mk)
* [v3.0.3](https://github.com/reactioncommerce/reaction-development-platform/blob/v3.0.3/config.mk)
* [v3.0.4](https://github.com/reactioncommerce/reaction-development-platform/blob/v3.0.4/config.mk)

This PR doesn't change anything about the general Reaction release process, lock-stepping or otherwise. The versioned file exists either at a tag, or in a directory. By placing them in a directory, we can run _any_ Reaction version with the latest `reaction-development-platform`.

**Comment by ticean** [comment]
The default configuration `config.mk` is the latest release. The content is copied, not symlinked.

**Comment by rosshadden** [comment]
I'm worried that having each Reaction version be a separate file would inflate files in this project for little gain. Will people really want to run Reaction API v3.0.0 when we are on v7.8.9? And is there a reason they couldn't just check out an earlier version of this repo or a tag on this repo?

**Review by focusaurus — APPROVED** [review]

**Comment by ticean** [comment]
> Will people really want to run Reaction v3.0.0 when we are on v7.8.9?

🤷‍♀ Maybe. We know of deployments today that are on older releases.

This project could be considered a "runner", like `npm` or `docker-compose` and has features that are separate from Reaction's features. We'll benefit by decoupling the runner from that being run. (Like, it's good that we don't have to bump `npm` when we change a node project.)

To illustrate a problem with the current tag model... this PR adds `make` tasks to get the local project state up to date with the configured git config. That's really useful. But, there's no way that you could use that functionality with Reaction 3.0.0, because the task doesn't exist in that platform tag.  After this merge, the new make tasks will work on any Reaction >=3.0.0 (and older if someone creates the config files.)

----

(We could go as far as to completely remove the configuration files from the project and store them somewhere else, but I don't think we'd get a good trade on that.)

**Comment by spencern** [comment]
@rosshadden I hear your concern on this. I've got a few related questions or thoughts disguised as questions.
1. Disregarding the potential that this approach has to increase the number of files in this project, does this proposal seem to solve a real issue to you?
2. Could we consider how to deal with the number of files in this project as a separate issue to deal with in the future if/when it becomes a problem, or do you believe it's a consideration that needs to be made now?

**Comment by kieckhafer** [comment]
I think @spencern's idea of dealing with the file number later would be OK. We make no guarantees of support on this project (I don't think), so having to bump to 4.0 and 5.0 and 6.0 if we move things around shouldn't be a big deal.

As for @rosshadden 's concern, I agree with Ticean and think that because this is a development platform, it's more likely to have people wanting to check out older versions to match what they are currently running.

**Review by kieckhafer — APPROVED** [review]

**Comment by rosshadden** [comment]
> Could we consider how to deal with the number of files in this project as a separate issue to deal with in the future if/when it becomes a problem?

Big yes. :+1:  :heavy_check_mark:

**Review by rosshadden — APPROVED** [review]

**Comment by ticean** [comment]
Looks like we have a consensus. I hear your concerns @rosshadden. We can evaluate the number of configurations and figure something out if it gets too unwieldy. This decision isn't a difficult one to back out of, so we can give this some time and then evaluate how it's going. Thanks to everyone for your input and review!

**Pull request merged**
