### PR TITLE
feat: removing hydra and identity

### PR DESCRIPTION
**Pull request by Akarshit**
BREAKING CHANGE: hydra and identity are no longer supported by the platform

Signed-off-by: Akarshit Wal <akarshitwal@gmail.com>

Impact: **breaking**  
Type: **feature**

## Testing
1. Try running various commands of the platform like `make init-dev`, `make`, `make stop`, `make clean`.
2. Make sure identity and hydra services are not started.

### CODE REVIEW

**Comment by MohanNarayana** [comment]
@Akarshit the services start up using the make commands but reaction-admin fails to load on the browser. Storefront works as expected.

**Review by MohanNarayana — APPROVED** [review]
Looking great!

**Comment by ismailsabry** [comment]
I was checking out what reaction is capable of, so I was following the [quick start guide](https://mailchimp.com/developer/open-commerce/guides/quick-start/), Running `make` did not show any errors but the admin dashboard didn't work in the browser as shown in the guide so I got confused. I checked docker ps and I saw that the dashboard was running however hydra and reaction-identity where not. I checked the logs for the reaction-admin container and I noticed that it was trying to connect to hydra so I kept investigating only to find this to be the root cause of the issue.

If you are going to make a breaking change, do not make it to the main project branch. Especially in a repo that sets the first impression of a large project. I spent over an hour investiganting this and it left me with a bad first impression of this project.

**Comment by Akarshit** [comment]
@ismailsabry You are absolutely correct. It was an oversight on my part to let that PR in. Great job figuring out the issue and getting around it.
Apologies for the bad experience and your wasted time, I have fixed the issue in #177.

I hope you give this project another shot, it's really worth it. Also we would be setting up better policy so that breaking changes do not make it into the main branch.

**Pull request merged**
